-- 작성된 커리문 실행하는 방법
-- 1. 블록잡고 Ctrl + Enter
-- 2. 페이지 전체 실행 Ctrl + shift + Enter

-- 스크립트 파일(.sql) 실행하는 방법 (mysql shell 활용)
-- 1. 명령 프롬프트(cmd) 열기
-- 2. 사용자 접속하기 
    -- mysql -u 사용자이름 -p 
    -- Enter password : **** 
-- 3. 접속 성공하면 MySQL Shell 로 진입함
	-- mysql> 
-- 4. 스크립트 파일 실행 명령 내리기
    -- mysql> source /path/스크립트파일명.sql    